# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_user', '0002_auto_20181227_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='Form_zhuangtai',
            field=models.CharField(default='取消订单', max_length=4, verbose_name='订单状态'),
        ),
    ]
