# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_user', '0003_forms_form_zhuangtai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='Form_zhuangtai',
            field=models.CharField(default='取消订单', max_length=5, verbose_name='订单状态'),
        ),
    ]
