# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GoodsName', models.CharField(max_length=35, verbose_name='商品名称')),
                ('Goodslogo', models.ImageField(default='/static/Images/shop_seller/shopImg.jpg', upload_to='static/shop_seller/images/GoodsImage/Goods/', verbose_name='商品图片')),
                ('GoodsContent', tinymce.models.HTMLField(null=True, verbose_name='商品详情')),
                ('GoodsStock', models.IntegerField(default=0, verbose_name='商品库存')),
                ('Goods_State', models.CharField(default='下架', max_length=10, verbose_name='商品状态')),
                ('Goods_brand', models.CharField(max_length=20, null=True, verbose_name='商品品牌')),
                ('Goods_size', models.CharField(default='均码', max_length=5, verbose_name='商品尺码')),
                ('Goods_price', models.FloatField(default=0, verbose_name='商品单价')),
                ('Goods_Type', models.CharField(default='外套', max_length=30, verbose_name='商品类型')),
            ],
            managers=[
                ('Goods_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Shoper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(default='123456', max_length=30)),
                ('ShopName', models.CharField(max_length=30)),
                ('LogoImg', models.ImageField(default='/static/Images/shop_seller/shopImg.jpg', upload_to='static/shop_seller/images/GoodsImage/GoodsLogo/')),
                ('Shop_introduce', models.CharField(max_length=254)),
                ('Shop_Content', tinymce.models.HTMLField()),
                ('Shop_RegistTime', models.DateTimeField(auto_now=True)),
                ('Shop_phone', models.CharField(max_length=12)),
            ],
            managers=[
                ('Shop_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='Goods_Shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_seller.Shoper'),
        ),
    ]
