# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='Goods_Shop_id',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='shop_seller.Shoper'),
        ),
    ]
