# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_seller', '0002_auto_20181227_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20, verbose_name='商品类型')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='Goods_State',
            field=models.CharField(default='已下架', max_length=10, verbose_name='商品状态'),
        ),
    ]
