# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_seller', '0003_auto_20181227_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='GoodsType',
            field=models.CharField(default='上衣', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='Type',
            field=models.CharField(default='毛衣', max_length=20, verbose_name='商品类型'),
        ),
    ]
